name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-on-npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        cli-arg: ['js', 'ts']
        include:
          - cli-arg: js
            flags: '-t javascript -l -u jest -al -d false -a false -m npm'
          - cli-arg: ts
            flags: '-t typescript -l -u jest -al -d false -a false -m npm'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test beta version on npm with args ${{ matrix.flags }}
        if: github.ref != 'refs/heads/main'
        run: |
          npx gen-express-cli@beta test-${{ matrix.cli-arg }} ${{ matrix.flags }}
          cd test-${{ matrix.cli-arg }}
          npm run dev &
          sleep 10
          curl -s http://localhost:8000/api | grep -q "This is the API root!" || exit 1
          kill $(lsof -t -i:8000) || true

      - name: Test latest version on npm with args ${{ matrix.flags }}
        if: github.ref == 'refs/heads/main'
        run: |
          npx gen-express-cli@latest test-${{ matrix.cli-arg }} ${{ matrix.flags }}
          cd test-${{ matrix.cli-arg }}
          npm run dev &
          sleep 10
          curl -s http://localhost:8000/api | grep -q "This is the API root!" || exit 1
          kill $(lsof -t -i:8000) || true
